### ISSUE TITLE
Task list of making a sandbox

### ISSUE THREAD

**Issue by franzaurus** [franzaurus/lorem-ipsum#11]
- [x] Open the box
- [x] Fill in the sand
- [ ] Close the sandbox

Another set of task list
- [ ] Open the sandbox
- [ ] Unload the sand
- [ ] Close the box
